version: '3'

volumes:
  persistent-data:

services:
  rove-server:
    build:
      context: .
      dockerfile: cmd/rove-server/Dockerfile
    image: rove-server:latest
    ports:
      - "80:80"
    command: ./rove-server --address ":80" --data=/mnt/rove-server ${ROVE_ARGS}
    volumes:
      - persistent-data:/mnt/rove-server:rw
