version: '3'

services:
  rove-server:
    build:
      context: .
      dockerfile: cmd/rove-server/Dockerfile
    image: rove-server:latest
    ports:
      - "80:80"
    command: ./rove-server --port 80
