version: '3'

volumes:
  persistent-data:

services:
  rove-server:
    build: .
    ports:
      - "80:80"
    command: ./rove-server --port 80 --data=/mnt/rove-server
    volumes:
      - persistent-data:/mnt/rove-server:rw
