version: '3'

volumes:
  persistent-data:

services:
  rove-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: rove:latest
    ports:
      - "9090:9090"
    environment:
      - PORT=9090
      - DATA_PATH=/mnt/rove-server
      - WORDS_FILE=data/words_alpha.txt
      - TICK_RATE=3
      - CERT_NAME=${CERT_NAME}
    volumes:
      - persistent-data:/mnt/rove-server:rw
      - /etc/letsencrypt/:/etc/letsencrypt/
    command: [ "./rove-server"]

  
