name: rove
title: Rove
base: core20
license: MIT
architectures: [ amd64 ]
# TODO icon:
summary: An asynchronous nomadic game about exploring as part of a loose community.
# TODO: Add more to the description
description: |
  An asynchronous nomadic game about exploring as part of a loose community.
confinement: strict
adopt-info: go-rove

apps:
  rove:
    command: bin/rove
    plugs: 
      - network
  rove-server:
    command: bin/rove-server
    plugs:
      - network
      - network-bind
  rove-accountant:
    command: bin/rove-accountant
    plugs:
      - network
      - network-bind
  rove-rest-server:
    command: bin/rove-reverse-proxy
    plugs:
      - network
      - network-bind

parts:
  go-rove:
    plugin: go
    source-type: local
    source: .
    build-packages:
      - gcc-multilib
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(git describe --always --long --dirty --tags)
      git describe --exact-match HEAD 2> /dev/null && snapcraftctl set-grade "stable" || snapcraftctl set-grade "devel"
      
    # TODO: Add the version into the build itself (currently using ldflags)
    # TODO: Server needs /usr/share/dict/words
