name: rove
base: core20
version: '0.1' # TODO: Set this up programatically
summary: An asynchronous nomadic game about exploring as part of a loose community.
# TODO: Add more to the description
description: |
  An asynchronous nomadic game about exploring as part of a loose community.
grade: devel # Upgrade to 'stable' when ready
confinement: strict

apps:
  rove:
    command: bin/rove
    plugs: 
      - network
  rove-server:
    command: bin/rove-server
    plugs:
      - network
      - network-bind
  rove-accountant:
    command: bin/rove-accountant
    plugs:
      - network
      - network-bind
  rove-rest-server:
    command: bin/rove-reverse-proxy
    plugs:
      - network
      - network-bind

parts:
  go-rove:
    plugin: go
    source-type: local
    source: .
    build-packages:
      - gcc-multilib
    # TODO: Add version somehow
    # TODO: Server needs /usr/share/dict/words
