name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Install dict
      run: sudo apt-get update && sudo apt-get install wamerican

    - name: Check out repo
      uses: actions/checkout@v2

    - name: Get go dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build and Test
      run: ./script/test.sh

    - name: Upload test coverage result
      uses: actions/upload-artifact@v1
      with:
        name: Coverage
        path: /tmp/coverage.html
