name: Docker

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        VERSION=$(git describe --always --long --dirty --tags)
        docker login docker.pkg.github.com -p ${{ secrets.GITHUB_TOKEN }}
        docker build . --tag rove:$VERSION --tag rove:latest
        docker push docker.pkg.github.com/mdiluz/rove/rove:$VERSION
        docker push docker.pkg.github.com/mdiluz/rove/rove:latest
