name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Get go dependencies
      run: |
        go get -v -t -d ./...

    - name: Build and Test
      run: make test

    - name: Upload test coverage result
      uses: actions/upload-artifact@v1
      with:
        name: Coverage
        path: /tmp/coverage.html
