name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Install swagger
      run: |
        sudo curl -o /usr/local/bin/swagger -L'#' https://github.com/go-swagger/go-swagger/releases/download/v0.23.0/swagger_linux_amd64
        sudo chmod +x /usr/local/bin/swagger

    - name: Check out repo
      uses: actions/checkout@v2

    - name: Install protoc and check no difference
      run: |
        sudo apt install protobuf-compiler
        make gen
        git update-index --refresh
        git diff-index --quiet HEAD --

    - name: Run golangci-lint
      uses: actions-contrib/golangci-lint@v1

    - name: Get go dependencies
      run: |
        go get -v -t -d ./...

    - name: Build and Test
      run: make test

    - name: Upload test coverage result
      uses: actions/upload-artifact@v1
      with:
        name: Coverage
        path: /tmp/coverage.html
